---
title: "Overview"
teaching: 45
exercises: 20
editor_options: 
  markdown: 
    wrap: 72
---


## Introduction

**Anticipated workshop duration when delivered to a group of participants is *3 hours***.

For queries relating to this workshop, contact Melbourne Bioinformatics ([bioinformatics-training\@unimelb.edu.au](mailto:bioinformatics-training@unimelb.edu.au)).

Find out when we are next running this training as an in-person workshop, by visiting the [Melbourne Bioinformatics Eventbrite page](https://www.eventbrite.com.au/o/melbourne-bioinformatics-xxxxxx).

------------------------------------------------------------------------

## Topic

-   [ ] Genomics
-   [ ] Transcriptomics
-   [ ] Proteomics
-   [ ] Metabolomics
-   [ ] Statistics and visualisation
-   [ ] Structural Modelling
-   [x] Basic skills

## Skill level

-   [x] Beginner
-   [ ] Intermediate
-   [ ] Advanced

This workshop is designed for participants with little or no command-line knowledge.

## Description

A hands-on workshop covering the basics of the Unix command line interface.

Knowledge of the Unix operating system is fundamental to the use of many popular bioinformatics command-line tools. Whether you choose to run your analyses locally or on a high-performance computing system, knowing your way around a command-line interface is highly valuable. This workshop will introduce you to Unix concepts by way of a series of hands-on exercises.

Completion of this workshop will provide the background knowledge required for several Melbourne Bioinformatics workshops that require command-line skills.

**Tools:** Standard Unix commands, [FileZilla](https://filezilla-project.org/)

**Topic overview:**

*Section 1:* Getting started\
*Section 2:* Exploring your current directory\
*Section 3:* Making and changing directories\
*Section 4:* Viewing and manipulating files\
*Section 5:* Removing files and directories\
*Section 6:* Searching files\
*Section 7:* Putting it all together\
*Section 8:* Transferring files
